// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnicczmbnjmctsnzyiip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuaWNjem1ibmptY3Rzbnp5aWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNjMwMzEsImV4cCI6MjA3MTczOTAzMX0.H8D1F-GPmtMasuPaPNWolf0x5q5JUw_m1nV8d5P2zx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});